name: Hello

on:
  push:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - id: app
        name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Get the authenticated user
        run: gh api /user
        env:
          GH_TOKEN: ${{ steps.app.outputs.token }}
      - name: GitHub App slug
        run: |-
          echo "app-slug: ${{ steps.app.outputs.app-slug }}"
