name: Hello

on:
  push:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - id: app
        name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
        continue-on-error: true
      - id: author
        name: Config Git Author
        run: |-
          export GIT_AUTHOR_NAME="${{ github.actor }}"
          export GIT_AUTHOR_EMAIL="${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          export GIT_AUTHOR="${GIT_AUTHOR_NAME} <${GIT_AUTHOR_EMAIL}>"
          echo "GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME}" >> "$GITHUB_ENV"
          echo "GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL}" >> "$GITHUB_ENV"
          echo "GIT_AUTHOR=${GIT_AUTHOR}" >> "$GITHUB_ENV"
          echo "author-name=${GIT_AUTHOR_NAME}" >> "$GITHUB_OUTPUT"
          echo "author-email=${GIT_AUTHOR_EMAIL}" >> "$GITHUB_OUTPUT"
          echo "author=${GIT_AUTHOR}" >> "$GITHUB_OUTPUT"
      - id: committer
        name: Configure Git Committer
        run: |-
          if [[ "${{ steps.app.outcome }}" == "success" ]]; then
            app_slug="${{ steps.app.outputs.app-slug }}"
          else
            app_slug="github-actions"
          fi
          export GIT_COMMITTER_NAME="${{ steps.app.outputs.app-slug }}[bot]"
          id=$(gh api --jq '.id' "/users/${GIT_COMMITTER_NAME}")
          export GIT_COMMITTER_EMAIL="${id}+${GIT_COMMITTER_NAME}@users.noreply.github.com"
          export GIT_COMMITTER="${GIT_COMMITTER_NAME} <${GIT_COMMITTER_EMAIL}>"
          echo "GIT_COMMITTER_NAME=${GIT_COMMITTER_NAME}" >> "$GITHUB_ENV"
          echo "GIT_COMMITTER_EMAIL=${GIT_COMMITTER_EMAIL}" >> "$GITHUB_ENV"
          echo "GIT_COMMITTER=${GIT_COMMITTER}" >> "$GITHUB_ENV"
          echo "committer-name=${GIT_COMMITTER_NAME}" >> "$GITHUB_OUTPUT"
          echo "committer-email=${GIT_COMMITTER_EMAIL}" >> "$GITHUB_OUTPUT"
          echo "committer=${GIT_COMMITTER}" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app.outputs.token || github.token }}
      - name: Echo Outputs
        run: |
          echo "author-name=${{ steps.author.outputs.author-name }}"
          echo "author-email=${{ steps.author.outputs.author-email }}"
          echo "author=${{ steps.author.outputs.author }}"
          echo "committer-name=${{ steps.committer.outputs.committer-name }}"
          echo "committer-email=${{ steps.committer.outputs.committer-email }}"
          echo "committer=${{ steps.committer.outputs.committer }}"
